language: python
services:
- docker
python:
- '3.6'
before_script:
- export LOCAL_POSTGRES_PORT_RANGE=5432
- docker-compose build
script:
- docker-compose run --rm web bash -c "python postgres_ready.py && ./manage.py migrate && ./manage.py test"
after_success:
- docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com
- docker tag web registry.heroku.com/skyrock_cluster/web
- docker push registry.heroku.com/skyrock_cluster/web
notifications:
  email: true
cache:
  pip: true