# Default values for service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployment:
  replicaCount: 1
  command: "['gunicorn', 'config.wsgi:application', '--config', 'file:config/gunicorn.py']"
image:
  repository: gcr.io/skyrock/skyrock_cluster
  tag: latest
  pullPolicy: IfNotPresent
service: 
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 8000
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8000
    initialDelaySeconds: 10
    timeoutSeconds: 2
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readiness
      port: 8000
    initialDelaySeconds: 10
    timeoutSeconds: 2
    periodSeconds: 10
ingress:
  enabled: true
  hosts:
    - localhost
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
  tls:
    - hosts:
      - localhost
      secretName: skyrock-service-tls
  hosts:
    - localhost
postgres:
  enabled: true
  user: admin
  host: patroni-skyrock-patroni.skyrock-staging
  port: "5432"
  secret:
    name: patroni-skyrock-patroni
    key: password-admin
workersEnabled: false
