# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-07 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='studentpathway',
            name='pathway',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='payment',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='hours',
            new_name='hours_remaining',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='code',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_pathway',
        ),
        migrations.AddField(
            model_name='booking',
            name='identifier',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pathway',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='identifier',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skyrock.Parent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='hours_spent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyrock.Student'),
        ),
        migrations.DeleteModel(
            name='StudentPathway',
        ),
        migrations.AddField(
            model_name='student',
            name='badges',
            field=models.ManyToManyField(blank=True, to='skyrock.Badge'),
        ),
    ]
