# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-07 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import skyrock.enums


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0002_auto_20190507_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hours', models.IntegerField()),
                ('location', enumfields.fields.EnumField(default='none', enum=skyrock.enums.Location, max_length=50)),
                ('current', models.BooleanField(default=True)),
                ('teacher', models.CharField(blank=True, db_index=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='pathway',
            name='current',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pathways',
        ),
        migrations.AlterField(
            model_name='parent',
            name='location',
            field=enumfields.fields.EnumField(default='none', enum=skyrock.enums.Location, max_length=50),
        ),
        migrations.AddField(
            model_name='program',
            name='pathway',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skyrock.Pathway'),
        ),
        migrations.AddField(
            model_name='program',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyrock.Student'),
        ),
    ]
