# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-24 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0003_auto_20190507_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='class_type',
            new_name='pathway',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hours_remaining',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hours_spent',
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_condition',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
