# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-03-19 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import enumfields.fields
import skyrock.enums
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0004_auto_20190215_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='colors',
        ),
        migrations.AddField(
            model_name='parent',
            name='identifier',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='identifier',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=enumfields.fields.EnumField(default='student', enum=skyrock.enums.Role, max_length=50),
        ),
    ]
