# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-24 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0004_auto_20190624_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='pathway',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
