# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-24 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0006_auto_20190624_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='medical_condition',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
