# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-03-25 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import enumfields.fields
import skyrock.enums


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0007_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=enumfields.fields.EnumField(default='present', enum=skyrock.enums.Attendance_status, max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='pathway',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
