# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-24 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0007_auto_20190624_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='hours',
        ),
    ]
