# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-25 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0008_remove_pathway_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
