# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-21 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0011_auto_20190821_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='client',
            name='language',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
