# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-02 03:40
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import skyrock.enums


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0012_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=enumfields.fields.EnumField(default='student', enum=skyrock.enums.Role, max_length=50),
        ),
    ]
