# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-06 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import skyrock.enums


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0013_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', enumfields.fields.EnumField(enum=skyrock.enums.Location, max_length=50)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='badge',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='project',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='studentbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='studentbadge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentchallenge',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='studentchallenge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentcolor',
            name='color',
        ),
        migrations.RemoveField(
            model_name='studentcolor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studenttask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='studenttask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.AddField(
            model_name='pathway',
            name='hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='StudentBadge',
        ),
        migrations.DeleteModel(
            name='StudentChallenge',
        ),
        migrations.DeleteModel(
            name='StudentColor',
        ),
        migrations.DeleteModel(
            name='StudentProject',
        ),
        migrations.DeleteModel(
            name='StudentTask',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='sale',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyrock.Pathway'),
        ),
        migrations.AddField(
            model_name='sale',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyrock.Student'),
        ),
    ]
