# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-22 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0014_auto_20190822_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='notes',
            new_name='language',
        ),
    ]
