# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-26 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0019_booking_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyrock.Club'),
        ),
    ]
