# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-03 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0022_auto_20190902_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='name',
        ),
    ]
