# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-03 03:04
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import skyrock.enums


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0023_remove_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='name',
            field=enumfields.fields.EnumField(default='None', enum=skyrock.enums.Clubs, max_length=50),
        ),
    ]
