# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-08 09:28
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import skyrock.enums


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0025_auto_20190908_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='club',
            field=enumfields.fields.EnumField(default='None', enum=skyrock.enums.Clubs, max_length=50),
        ),
    ]
